version: 2.1
jobs:
  main_script:
    docker:
      - image: cimg/node:21.5.0 # specify the version of Node.js
    steps:
      - checkout
      # - run:
      #     name: Install Dependencies
      #     command: npm install
      - run:
          name: Run Node.js Script
          command: node yourfile.js
workflows:
  version: 2
  build:
    jobs:
      - main_script
