version: 2.1
jobs:
  main_script:
    docker:
      - image: cimg/node:21.5.0 # specify the version of Node.js
    steps:
      - checkout
      - run:
          name: Install System Fonts
          command: |
            sudo apt-get update
            sudo apt-get install -y fontconfig
            sudo apt-get install -y libfontconfig1

      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Node.js Script
          command: node main.js
workflows:
  version: 2
  build:
    jobs:
      - main_script:
          filters:
            branches:
              only:
                - main
      
